In [1]:
p=[]
n=5

for i in range(n):
    p.append(1/n)

print(p)

[0.2, 0.2, 0.2, 0.2, 0.2]


In [10]:
import numpy as np

In [6]:
p_hit=0.6
p_miss=0.2
p[0]*=p_miss
p[1]*=p_hit
p[2]*=p_hit
p[3]*=p_miss
p[4]*=p_miss
print(p)

[6.400000000000002e-05, 0.12, 0.015551999999999996, 0.00864, 0.00032000000000000013]


In [44]:
world=['green','red','red','green','green']
p=[]
n=5
for i in range(n):
    p.append(1/n)
    
z='red'

p_hit=0.6
p_miss=0.2
def sense(p,z):
    q=[]
    for i in range(len(p)):
        hit=(z==world[i])
        q.append(p[i]*(hit*p_hit+(1-hit)*p_miss))
    return q
print(sense(p,z))

[0.04000000000000001, 0.12, 0.12, 0.04000000000000001, 0.04000000000000001]


In [63]:
measurement=['red','green']
world=['green','red','red','green','green']
p=[]
n=5
for i in range(n):
    p.append(1/n)

z='red'
p_hit=0.6
p_miss=0.2
def sense(p,z):
    q=[]
    for i in range(len(p)):
        hit=(z==world[i])
        q.append(p[i]*(hit*p_hit+(1-hit)*p_miss))
    return np.array(q)/sum(q)

for k in range(len(measurement)):
    p=sense(p,measurement[k])
    print(p)

[0.11111111 0.33333333 0.33333333 0.11111111 0.11111111]
[0.2 0.2 0.2 0.2 0.2]


In [24]:
# deterministic move
def Dmove(p,U):
    q=[]
    for i in range(len(p)):
        q.append(p[(i-U)%len(p)])
    return q
p=[0,0,1,0,0]
move(p,3)

[1, 0, 0, 0, 0]

In [64]:
pExact=0.8
pOverShoot=0.1
pUnderShoot=0.1
# stochastic move
def Smove(p,U):
    q=[]
    for i in range(len(p)):
        s=pExact*p[(i-U)%len(p)]
        s+=pOverShoot*p[(i-U-1)%len(p)]
        s+=pUnderShoot*p[(i-U+1)%len(p)]
        q.append(s)
    return q
p=[0,0.5,0,0.5,0]
Smove(p,2)

[0.4, 0.05, 0.05, 0.4, 0.1]

In [40]:
# move repeatedly to see if we move with blind eyes then we are not sure 
# where we are after some iterations(but at first we knew where we were)
p=[1,0,0,0,0]
for i in range(3):
    p=Smove(p,1)
# print(p)
print(np.round(p,3))
p=[1,0,0,0,0]
for i in range(3):
    p=Dmove(p,1)
print(np.round(p,3))

[0.025 0.025 0.195 0.56  0.195]
[0 0 0 1 0]


In [57]:
p=[0.2,0.2,0.2,0.2,0.2]

motion=[1,1]
measurement=['red','red']
for k in range(len(measurement)):
    p=sense(p, measurement[k])
    p=Smove(p,motion[k])
print(np.round(p,3))

[0.2 0.2 0.2 0.2 0.2]
[0.04  0.048 0.112 0.112 0.048]
[0.011 0.01  0.031 0.059 0.026]
